name: document_processor
description: A web app for processing PDF and Office documents

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: '>=1.1.0 <2.0.0'
  provider: '>=6.1.1 <7.0.0'
  syncfusion_flutter_pdfviewer: '>=23.1.36 <24.0.0'
  syncfusion_flutter_signaturepad: '>=23.1.36 <24.0.0'
  universal_html: '>=2.2.1 <3.0.0'
  file_picker: '>=10.1.9 <11.0.0'
  path: '>=1.8.3 <2.0.0'
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
